kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mysql-info
data:
  # Configuration values can be set as key-value properties
  database: mysql
  database_uri: mongodb://localhost:27017
  mysqld_info: |-
    import pymysql.cursors

    con = pymysql.connect(
            host = '103.56.156.199',
            user = 'root',
            password = '123456',
            database = 'updownloadfile',
            cursorclass = pymysql.cursors.DictCursor
            )