kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mysql-info
data:
  # Configuration values can be set as key-value properties
  MYSQL_HOST: 103.56.156.199
  MYSQL_USER: root
  MYSQL_PASS: 123456
  MYSQL_DATABASE: updownloadfile
