apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: appdeploy
        image: cr-hn-1.bizflycloud.vn/f8a5a016b2274fd1a2b405e447e665fe/flaskapp:latest
        ports:
        - containerPort: 5000 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-info
                key: MYSQL_HOST
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-info
                key: MYSQL_USER
          - name: MYSQL_PASS
            valueFrom:
              configMapKeyRef:
                name: mysql-info
                key: MYSQL_PASS
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-info
                key: MYSQL_DATABASE


