apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: appdeploy-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appdeploy
  minReplicas: 1
  maxReplicas: 13
  targetCPUUtilizationPercentage: 50
